[project]
name = "generate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.2.1",
    "dicttoxml>=1.7.16",
    "faker>=37.4.0",
]
